### PR TITLE
Fix clone-buffer error when dired-quick-sort, dired-collapse-mode ...

### PR DESCRIPTION
**Pull request by deftsp**

### CODE REVIEW

**Comment by jojojames** [comment]
I wonder if we **want** other hooks to run but just have a blacklist of hooks to remove?

**Comment by deftsp** [comment]
Let's do a simple test.  For a function `foo`, it just set a buffer local variable  `bar` to a integer. Add function foo to `dired-mode-hook`. After `clone-buffer`, the new created `dired-side-bar` buffer have the correct `bar` value. So, I think the hook functions have already been run.

I have used the the patch for a while, haven't found the side effect until now.

**Comment by jojojames** [comment]
Hmnn not sure I grok what you're saying. Are you running that^ with your patch? Shouldn't the hook **not** run with your patch?

**Comment by deftsp** [comment]
Sure, I'm using my patched branch now. In fact I'm not sure the idea of blacklist the hooks. However, add a  custom variable like  'dired-sidebar-protected-command'. let user to add  "problem"  hooks such as `dired-quick-sort` and dired-collapse-mode.

**Comment by jojojames** [comment]
Yeah you can do that or hardcode it for now. I guess the implementation would involve checking which hooks need to be removed and then re-adding them after clone.

**Comment by deftsp** [comment]
Fair enough.  I'll use the blacklist hooks version for a peroid of time to test more. 

close the pull now.

**Comment by jojojames** [comment]
Thanks sounds good !

**Pull request closed without merging**
